### PR TITLE
creates CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by lwinfree**
adds the code of conduct
@roll

### CODE REVIEW

**Comment by roll** [comment]
Hey @lwinfree, maybe it's better to link the one on the website from all our repos as we e.g. for the chat? Otherwise, it will be dozens of copies of this document we need to maintain. WDYT?

**Comment by lwinfree** [comment]
@roll I had the same thought after I opened this issue, so I wanted to ask you this week. I have added the CoC link to the main repo page. The only reason to add the CoC to the individual repos is so people automatically scrapping/looking for the CoC can find it. But it does seem like a ton of work to put it on each repo & then maintain it. WDYT?

**Comment by roll** [comment]
@lwinfree 
Yea, I think we better link at least, for now. When we have fewer repositories we can get back to the idea of putting it into the code. WDYT?

**Comment by chris48s** [comment]
This is the approach we did at my previous job: Put a  `CODE_OF_CONDUCT.md` in every repo saying "Please read and follow our [Code of Conduct](https://okfn.org/about/code-of-conduct/)." Then github reports that you have one, but if you change it, you only have to do it in one place.

Side note: If there are standard files we want to put in every repo, e.g: `CODE_OF_CONDUCT.md`, issue/PR template files, `funding.yml` you can create a repo `frictionlessdata/.github` and put them in there then every new repo will inherit them. Example of this: https://github.com/standard/.github/
Obviously we still need to do it manually for existing repos.

**Comment by roll** [comment]
I'm curious if we can put them into .github/CODE_OF_CONDUCT

**Comment by roll** [comment]
> I'm curious if we can put them into .github/CODE_OF_CONDUCT
It worked. FIXED

**Pull request closed without merging**
