### PR TITLE
Stopped locking dependencies versions

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by roll** [comment]
Thanks!

@akariv 
WDYT?

I think for Python our strategy too aggressive.
At least we need to drop the `maximum` version.

**Comment by akariv** [comment]
You're probably right @roll - 
The maximum version was originally there for things to be more predictable and not break when a dependency updates, bu usually what happens is that get a version mismatch with another library and things break anyway...

**Comment by organman91** [comment]
It looks like this breaks things with the recent release of jsonschema. Running `pip install 'datapackage<2.0,>=1.2'` gives the warning 'tableschema 1.4.0 has requirement jsonschema<3.0,>=2.5, but you'll have jsonschema 3.0.1 which is incompatible.'

**Comment by KOLANICH** [comment]
Yet another argument against version locking. It is `tableschema` issue that it locks packages to old versions.

**Pull request closed without merging**
