### PR TITLE
Use descriptor, not metadata, to stay close to spec semantics.

### LINKED ISSUE #88: Rename metadata to descriptor
We put the descriptor on the `metadata` property of a `DataPackage` to prevent clashes with other method names. I think we should rename `metadata` to `descriptor`, which is consistent with the DP terminology and less confusing IMHO.

- https://github.com/frictionlessdata/datapackage-py/blob/master/datapackage/datapackage.py#L26
- https://github.com/frictionlessdata/datapackage-py/blob/master/datapackage/datapackage.py#L66

@vitorbaptista @roll @rgrp thoughts?

### PR DESCRIPTION
**Pull request by pwalsh**
Fixes #88.

@vitorbaptista @roll @amercader @akariv for review.

### CODE REVIEW

**Comment by roll** [comment]
@pwalsh 
looks good for me

- also I've found metadata term in `registry` code - I'm not sure should it be also replaces
- version could be bumped to `0.7.0` inside the PR if you prefer to release

**Comment by pwalsh** [comment]
@roll i left the registry stuff on purpose.

**Comment by vitorbaptista** [comment]
Looks good to me as well, but I was thinking: does a "resource's descriptor" make sense? We use this term for the datapackage itself, but am not sure if we use it for resources as well.

Even if not, I don't like using `descriptor` for the datapackage and `metadata` for the resources.

**Comment by pwalsh** [comment]
@vitorbaptista yes, it does. I get your point, but resource as a concept to contain data + schema (int he tabular data case) is increasingly emerging as one of the most useful aspects of the spec work, to the point that we'll likely also start describing a "resource object" as either a spec, or a "pattern" ( cc @rgrp )

**Comment by vitorbaptista** [comment]
@pwalsh In that case, I'm happy to merge this. We will probably need to update `ckanext-datapackager` as well when a new version is published with these changes.

**Pull request merged**
