### PR TITLE
Add Linear TSV format support

### PR DESCRIPTION
**Pull request by sirex**
See: http://dataprotocols.org/linear-tsv/

Depends on:

- https://github.com/frictionlessdata/tabulator-py/pull/54
- https://github.com/solidsnack/tsv/pull/2

### CODE REVIEW

**Comment by roll** [comment]
Thanks! Great contribution.

 It looks like we have only `https://github.com/solidsnack/tsv` tsv parser for python?

**Comment by sirex** [comment]
@roll I did a quick search http://pypi-ranking.info/search/tsv/

And found two tsv parsers for python, [the other one](https://pypi.python.org/pypi/tsv/) last updated in 2013.

**Comment by vitorbaptista** [comment]
@sirex Thanks for the PR, it looks great.

Apart from the failures in Travis, could you add the tests in the `TestTabularResource` in https://github.com/frictionlessdata/datapackage-py/blob/master/tests/test_resource.py#L355 instead of as a new file? Just move the `test_tsv` function you've created (and rename it to `test_load_tsv`).

**Comment by roll** [comment]
Guys, I'll ping when tabulator will be released to PyPi making this PR working.

**Comment by roll** [comment]
https://pypi.python.org/pypi/tabulator/0.4.0

**Comment by vitorbaptista** [comment]
This look great! @sirex could you rebase and fix the conflicts with master, so I can merge it in?

**Comment by sirex** [comment]
@vitorbaptista done.

**Comment by vitorbaptista** [comment]
Thanks for your work, @sirex. Great job! :clap:

**Pull request merged**
