### PR TITLE
Fix failed to load profile's error message

### PR DESCRIPTION
**Pull request by vitorbaptista**

### CODE REVIEW

**Comment by roll** [comment]
It seems we need to drop Py3.3

**Comment by vitorbaptista** [comment]
@roll I agree. Even Python and Pytest itself dropped support already (see https://github.com/pytest-dev/pytest-mock/pull/96)

**Comment by roll** [comment]
Would you like to commit? 

I'll merge and release straight after.

**Comment by vitorbaptista** [comment]
@roll All good now :+1:

**Pull request merged**
